version: '3'

services:
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 3s
      timeout: 10s
      retries: 3

  consumer:
    build: consumer
    volumes:
      - ./consumer:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure
    depends_on:
      - rabbitmq

  producer:
    build: producer
    volumes:
      - ./producer:/app
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - rabbitmq